### ISSUE TITLE
Make compatible with Python 3.5

### ISSUE THREAD

**Issue by JarnoRFB** [JarnoRFB/incense#26]
Using https://github.com/asottile/future-fstrings

**Comment by JarnoRFB** [comment]
Or maybe not, because dictionary insertion order was not there yet.

**Comment by mdbenito** [comment]
Hi! Is incense supposed to support Python 3.5?  There are a bunch of f-strings in the code... Have you decided not to support it? Requiring 3.6 makes docker images based on distros running 3.5 quite larger...

**Comment by JarnoRFB** [comment]
Hi, unofficially Python 3.5 is supported, though I do not want to commit to supporting it officially, as this brings other liabilities. f-strings are made to work with py35 using the `future-fstrings` package.

**Comment by mdbenito** [comment]
I've seen that future-fstrings is used, but for some reason it does not always work. In an ubuntu 16 based container with python 3.5.2 installed and `pip3 install incense==0.0.8` ran, the encoding magic at is not picked.

However, I just found out the problem: having `tokenize-rt==3.0.1` results in

```
69dc15f301f1:~$ python3
Python 3.5.2 (default, Aug 18 2017, 17:48:00) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import incense
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/incense/__init__.py", line 2, in <module>
    from .experiment_loader import ExperimentLoader
  File "/usr/local/lib/python3.5/dist-packages/incense/experiment_loader.py", line 87
    key = f"config.{key}"
                        ^
SyntaxError: invalid syntax
>>> 
```

Downgrading to 2.2.0 solved the issue 🤷‍♂️

Sorry for the noise!

**Comment by JarnoRFB** [comment]
Your welcome, though I do not really understand the problem with tokenize-rt...

**Comment by mdbenito** [comment]
Maybe it makes sense to add `tokenize-rt==2.2.0` to your requirements.txt. At least for me, letting pip install the latest from some other package's requirements breaks future-fstrings, and that version works perfectly fine.

**Comment by JarnoRFB** [comment]
Good idea! I did this in the latest commit. Thanks for reporting this!

**Comment by sancreations** [comment]
> Maybe it makes sense to add `tokenize`

downgrading tokenize-rt to 2.2.0 worked for me!
