### ISSUE TITLE
Deletion of experiments and caching

### ISSUE THREAD

**Issue by mdbenito** [JarnoRFB/incense#35]
Hi, first of all thanks for making incense.

It seems like there is some caching issue (maybe related to #16 ?). In a notebook:

```python
exps = loader.find_by_key("status", "FAILED")
print(len(exps))
for e in exps:
    e.delete(confirmed=True)
exps = loader.find_by_key("status", "FAILED")
print(len(exps))
```

outputs

```
714
714
```

Only after restarting the kernel does the query return 0 results.

**Comment by JarnoRFB** [comment]
Hi, thanks a lot for reporting! The issue should be fixed with the next PR.
