### ISSUE TITLE
Add filter method to QuerySet

### ISSUE THREAD

**Issue by vmasrani** [JarnoRFB/incense#39]
Great package! Would it be difficult to add a filter method to the QuerySet object? I'm imagining it would work similar to `exps.project(on=["experiment.name", "config.optimizer", "config.epochs"])`, except it takes a list of key:value pairs and return a filtered list of experiment objects. I often find myself loading all experiments of a particular name, then writing ugly for loops to further filter the list based on some criteria.

**Comment by JarnoRFB** [comment]
Hi, for such a use case I would recommend to use the `find` method of the `loader`. You can pass a custom mongo query that already works more or less as you described. And it gives you even more expressiveness by allowing connectors such as `$and` and `$or`. Additionally, you get the extra benefit of not having to load data from the database that you will discard anyway.  

For example loading all experiments that have a certain name and a certain number of epochs would work like this
```python
query = {"$and": [
            {"experiment.name": "my_exp_name"},
            {"config.epochs": 3},
        ]}
loader.find(query)
```
For a more complete reference take a look at https://docs.mongodb.com/manual/tutorial/query-documents/

**Comment by JarnoRFB** [comment]
Closing since it seems to be solved. @vmasrani  please tell me if this satisfies your requirement
