### ISSUE TITLE
Decoding numpy arrays require import sacred

### ISSUE THREAD

**Issue by vnmabus** [JarnoRFB/incense#58]
Sacred creates its own encoder to encode numpy arrays in experiments. Thus, if sacred is not imported before obtaining an experiment with numpy arrays in the info dict, those are not unpickled. I propose to import sacred, at least when unpickle is `True`.

**Comment by JarnoRFB** [comment]
@vnmabus thanks for notifying me. I was actually totally unaware of that. Should be fixed in master soon.
