### ISSUE TITLE
Release in PyPI

### ISSUE THREAD

**Issue by vnmabus** [JarnoRFB/incense#79]
The last release is not in PyPI. I suggest you to use a Github action to upload automatically to PyPI on release.

**Comment by JarnoRFB** [comment]
Hey, I would like to, but first needed to fix the build in general. PR is still in progress. Hopefully, will get to it on the weekend.

**Comment by JarnoRFB** [comment]
Meanwhile you can alwalys install the latest version from master using `pip install git+https://github.com/JarnoRFB/incense.git
`

**Comment by vnmabus** [comment]
Any news about this?

**Comment by JarnoRFB** [comment]
@JarnoRFB The new version should be finally release as [0.0.14](https://pypi.org/project/incense/0.0.14/). Let me know if it is missing anything and sorry for the long wait.
